using CS_maturita_test.Data;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;

namespace CS_maturita_test
{
    public class Program
    {
        public static void Main(string[] args)
        {
            var builder = WebApplication.CreateBuilder(args);

            var port = Environment.GetEnvironmentVariable("PORT");
            if (!string.IsNullOrEmpty(port))
            {
                builder.WebHost.UseUrls($"http://*:{port}");
            }

            builder.Services.AddDbContext<ApplicationDbContext>(options =>
                options.UseNpgsql(builder.Configuration.GetConnectionString("DefaultConnection")));

            builder.Services
                .AddIdentity<IdentityUser, IdentityRole>(options =>
                {
                    options.Password.RequireDigit = false;
                    options.Password.RequireLowercase = false;
                    options.Password.RequireUppercase = false;
                    options.Password.RequireNonAlphanumeric = false;
                    options.Password.RequiredLength = 1;
                    options.Password.RequiredUniqueChars = 0;
                })
                .AddEntityFrameworkStores<ApplicationDbContext>()
                .AddDefaultTokenProviders();

            builder.Services.AddControllersWithViews();

            var app = builder.Build();

            using (var scope = app.Services.CreateScope())
            {
                var db = scope.ServiceProvider.GetRequiredService<ApplicationDbContext>();

                db.Database.ExecuteSqlRaw(@"
                    CREATE TABLE IF NOT EXISTS ""AspNetRoles"" (
                        ""Id"" text NOT NULL,
                        ""Name"" character varying(256),
                        ""NormalizedName"" character varying(256),
                        ""ConcurrencyStamp"" text,
                        CONSTRAINT ""PK_AspNetRoles"" PRIMARY KEY (""Id"")
                    );

                    CREATE TABLE IF NOT EXISTS ""AspNetUsers"" (
                        ""Id"" text NOT NULL,
                        ""UserName"" character varying(256),
                        ""NormalizedUserName"" character varying(256),
                        ""Email"" character varying(256),
                        ""NormalizedEmail"" character varying(256),
                        ""EmailConfirmed"" boolean NOT NULL,
                        ""PasswordHash"" text,
                        ""SecurityStamp"" text,
                        ""ConcurrencyStamp"" text,
                        ""PhoneNumber"" text,
                        ""PhoneNumberConfirmed"" boolean NOT NULL,
                        ""TwoFactorEnabled"" boolean NOT NULL,
                        ""LockoutEnd"" timestamp with time zone,
                        ""LockoutEnabled"" boolean NOT NULL,
                        ""AccessFailedCount"" integer NOT NULL,
                        CONSTRAINT ""PK_AspNetUsers"" PRIMARY KEY (""Id"")
                    );

                    CREATE TABLE IF NOT EXISTS ""AspNetRoleClaims"" (
                        ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                        ""RoleId"" text NOT NULL,
                        ""ClaimType"" text,
                        ""ClaimValue"" text,
                        CONSTRAINT ""PK_AspNetRoleClaims"" PRIMARY KEY (""Id""),
                        CONSTRAINT ""FK_AspNetRoleClaims_AspNetRoles_RoleId"" FOREIGN KEY (""RoleId"") REFERENCES ""AspNetRoles"" (""Id"") ON DELETE CASCADE
                    );

                    CREATE TABLE IF NOT EXISTS ""AspNetUserClaims"" (
                        ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                        ""UserId"" text NOT NULL,
                        ""ClaimType"" text,
                        ""ClaimValue"" text,
                        CONSTRAINT ""PK_AspNetUserClaims"" PRIMARY KEY (""Id""),
                        CONSTRAINT ""FK_AspNetUserClaims_AspNetUsers_UserId"" FOREIGN KEY (""UserId"") REFERENCES ""AspNetUsers"" (""Id"") ON DELETE CASCADE
                    );

                    CREATE TABLE IF NOT EXISTS ""AspNetUserLogins"" (
                        ""LoginProvider"" text NOT NULL,
                        ""ProviderKey"" text NOT NULL,
                        ""ProviderDisplayName"" text,
                        ""UserId"" text NOT NULL,
                        CONSTRAINT ""PK_AspNetUserLogins"" PRIMARY KEY (""LoginProvider"", ""ProviderKey""),
                        CONSTRAINT ""FK_AspNetUserLogins_AspNetUsers_UserId"" FOREIGN KEY (""UserId"") REFERENCES ""AspNetUsers"" (""Id"") ON DELETE CASCADE
                    );

                    CREATE TABLE IF NOT EXISTS ""AspNetUserRoles"" (
                        ""UserId"" text NOT NULL,
                        ""RoleId"" text NOT NULL,
                        CONSTRAINT ""PK_AspNetUserRoles"" PRIMARY KEY (""UserId"", ""RoleId""),
                        CONSTRAINT ""FK_AspNetUserRoles_AspNetRoles_RoleId"" FOREIGN KEY (""RoleId"") REFERENCES ""AspNetRoles"" (""Id"") ON DELETE CASCADE,
                        CONSTRAINT ""FK_AspNetUserRoles_AspNetUsers_UserId"" FOREIGN KEY (""UserId"") REFERENCES ""AspNetUsers"" (""Id"") ON DELETE CASCADE
                    );

                    CREATE TABLE IF NOT EXISTS ""AspNetUserTokens"" (
                        ""UserId"" text NOT NULL,
                        ""LoginProvider"" text NOT NULL,
                        ""Name"" text NOT NULL,
                        ""Value"" text,
                        CONSTRAINT ""PK_AspNetUserTokens"" PRIMARY KEY (""UserId"", ""LoginProvider"", ""Name""),
                        CONSTRAINT ""FK_AspNetUserTokens_AspNetUsers_UserId"" FOREIGN KEY (""UserId"") REFERENCES ""AspNetUsers"" (""Id"") ON DELETE CASCADE
                    );

                    CREATE TABLE IF NOT EXISTS ""Notes"" (
                        ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                        ""Title"" text NOT NULL,
                        ""Content"" text NOT NULL,
                        ""UserId"" text NOT NULL,
                        ""IsImportant"" boolean NOT NULL DEFAULT FALSE,
                        ""CreatedAt"" timestamp with time zone NOT NULL,
                        CONSTRAINT ""PK_Notes"" PRIMARY KEY (""Id""),
                        CONSTRAINT ""FK_Notes_AspNetUsers_UserId"" FOREIGN KEY (""UserId"") REFERENCES ""AspNetUsers"" (""Id"") ON DELETE CASCADE
                    );

                    CREATE INDEX IF NOT EXISTS ""IX_AspNetRoleClaims_RoleId"" ON ""AspNetRoleClaims"" (""RoleId"");
                    CREATE UNIQUE INDEX IF NOT EXISTS ""RoleNameIndex"" ON ""AspNetRoles"" (""NormalizedName"");
                    CREATE INDEX IF NOT EXISTS ""IX_AspNetUserClaims_UserId"" ON ""AspNetUserClaims"" (""UserId"");
                    CREATE INDEX IF NOT EXISTS ""IX_AspNetUserLogins_UserId"" ON ""AspNetUserLogins"" (""UserId"");
                    CREATE INDEX IF NOT EXISTS ""IX_AspNetUserRoles_RoleId"" ON ""AspNetUserRoles"" (""RoleId"");
                    CREATE INDEX IF NOT EXISTS ""EmailIndex"" ON ""AspNetUsers"" (""NormalizedEmail"");
                    CREATE UNIQUE INDEX IF NOT EXISTS ""UserNameIndex"" ON ""AspNetUsers"" (""NormalizedUserName"");
                    CREATE INDEX IF NOT EXISTS ""IX_Notes_UserId"" ON ""Notes"" (""UserId"");
                ");
            }

            // Configure the HTTP request pipeline.
            if (!app.Environment.IsDevelopment())
            {
                app.UseExceptionHandler("/Home/Error");
                // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
                app.UseHsts();
            }

            app.UseHttpsRedirection();
            app.UseStaticFiles();

            app.UseRouting();

            app.UseAuthentication();
            app.UseAuthorization();

            app.MapControllerRoute(
                name: "default",
                pattern: "{controller=Home}/{action=Index}/{id?}");

            app.Run();
        }
    }
}
